### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by SuggeElson** [sultantarimo/cssCharts.js#3]
Great start but can you make it responsive i.e 100% width.

**Comment by thysultan** [comment]
update: made line chart responsive. @SuggeElson

**Comment by SuggeElson** [comment]
How this work ? i see your plugin define the with to .chart class
class="chart line" style="width: 640px; height: 220px

**Comment by thysultan** [comment]
@SuggeElson  For example if you where to add this to your stylesheet 

```
.chart{width:400px;} 
  or
 #chartId{width:400px;}
```

it will scale with it respectively

**Comment by SuggeElson** [comment]
I know but when try to resize it dynamic plugin redraw the lines correct but not the points.

**Comment by thysultan** [comment]
If you where to do for example:

```
$(window).resize(function(){
    $('.line-chart').cssCharts({type:"line"});
});
```

You would see it update/redraw when you resize the window.
