### ISSUE TITLE
Data-percentage Error

### ISSUE THREAD

**Issue by gouthamai** [sultantarimo/cssCharts.js#9]
### When we set the data-percentage to 0.14. the donut chart displays as 14.000000000000002% instead of 14%

We used the below code to get it fixed.

**Line no 192 :** 
`$({countNum: $title.find("p").text()}).animate({countNum: val/360*100}, {`
**to**
`$({countNum: $title.find("p").text()}).animate({countNum: parseFloat(val/360*100).toFixed(2)}, {`

**Comment by thysultan** [comment]
Fixed.
